name: Artifact
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  DOTNET_VERSION: '5.0.301' # The .NET SDK version to use

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
      
    - name: Publish
      run: dotnet publish
